[jobs.run]
command = ["cargo", "run", "-p", "api"]
need_stdout = true
allow_warnings = true
on_change_strategy = "kill_then_restart"
watch = ["api/src", "api/Cargo.toml", "api_schema/src", "api_schema/Cargo.toml", "Cargo.toml"]
