services:
  api:
    build:
      context: .
      dockerfile: ./containers/api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-test:
    build:
      context: .
      dockerfile: ./containers/api-test/Dockerfile
    volumes:
      - ./application/api_test:/app/api_test:cached
    networks:
      - api-network
    profiles:
      - test
    depends_on:
      api:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=graphql_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - api-network

volumes:
  postgres-data:

networks:
  api-network:
    driver: bridge