name: Claude PR Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@v1-dev
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request using the code-reviewer agent.

            Note: The PR branch is already checked out in the current working directory.

            Use the Task tool to invoke the code-reviewer agent with the following context:
            - REPO: ${{ github.repository }}
            - PR NUMBER: ${{ github.event.pull_request.number }}
            - Request a comprehensive code review focusing on the changes in this PR
            
            After receiving the review from the code-reviewer agent, post the findings as GitHub comments:
            - Use `gh pr comment:*` for the overall review summary
            - Use `mcp__github_inline_comment__create_inline_comment` to highlight specific areas of concern
            
            Only your GitHub comments that you post will be seen, so make sure to convert the agent's review into appropriate GitHub comments.
            If the PR has already been reviewed, or there are no noteworthy changes, don't post anything.

          claude_args: |
            --allowedTools "Task,mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"